from backports.cached_property import cached_property
from typing import TYPE_CHECKING, List, Set
from .autogenerated_models import *


if TYPE_CHECKING:
    from .api import E621API


class EnrichedPost(Post):
    @cached_property
    def all_tags(self) -> Set[str]:
        return set(
            self.tags.general
            + self.tags.species
            + self.tags.character
            + self.tags.copyright
            + self.tags.artist
            + self.tags.invalid
            + self.tags.lore
            + self.tags.meta
        )

    def get_name(self, i: int) -> str:
        return f"{i} {self.id}.{self.file.ext}"


class EnrichedPool(Pool):
    _e6api: "E621API"

    @cached_property
    def posts(self) -> List[EnrichedPost]:
        return self._e6api.get_posts(f"id:{','.join(map(str, self.post_ids))}")
